### ISSUE TITLE
Action does not update or remove the comment when PR has zero changes

### ISSUE THREAD

**Issue by madhusudhand** [vcanales/action-wp-playground-pr-preview#19]
When PR is updated with zero theme changes it fails to update the comment.

#### Steps:

* Create a PR with a change to a theme and another file such as `readme.md`
* Action adds a comment with one preview link
* Now revert the theme change and update the PR (now PR has only change to readme.md)
* Observe that action fails to update the comment.

#### Expectation:

Action should remove the comment when there are no theme changes, and if there is a previous comment in the PR.
Alternatively, it may also update the comment to remove all links and just say `no theme changes`

**Comment by vcanales** [comment]
Thanks for the report, I've updated the action with a couple of improvements. https://github.com/vcanales/action-wp-playground-pr-preview/pull/22

- Better diffing: we will no longer see irrelevant changes being displayed because we now compare the branch `HEAD` with the base ref from which the branch was created instead of the base branch.
- Added a delete step that removes the comment if no theme changes are detected.
